tickets:
  panel_title: "Panel Title"
  panel_message: "Panel Message"
  questionnaire_title: "Questionario"
  modal_answer: "Your ticket channel has been successfully created, you can click the button below to be redirected"
  user_added: "The user was successfully added to the ticket!"
  user_removed: "The user was successfully removed from the ticket!"
  ticket_claimed: "The ticket was successfully claimed!"
  ticket_unclaimed: "The ticket was unclaimed sccessfully!"
  ticket_closed: "The ticket was successfully closed!"
  ticket_reopened: "The ticket was successfully reopened!"